import type { NextPage } from "next";
import { Fragment } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import components
import About from "../components/about";
import Tools from "../components/tools";
import RecentWorks from "../components/recentWorks";
import SayHi from "../components/sayHi";
import Footer from "../components/footer";
const Home: NextPage = () => {
  return (
    <Fragment>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className="2xl:px-[500px]  xl:px-[500px] lg:px-[500px] md:px-[500px] sm:px-5   ">
        <div className="intro py-[200px] sm:py-11  ">
          <p className="text-globalOrange">Hi my name is </p>
          <h1 className="font-bold text-9xl py-3 sm:text-6xl">Vikash Surin</h1>
          <p>i design and write code.</p>
        </div>
        <About />
        <Tools />
        <RecentWorks />
        <SayHi />
        <Footer />
      </main>
{/* 
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </Fragment>
  );
};

export default Home;
